apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: products-service
  name: products-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - image: 048443535585.dkr.ecr.eu-north-1.amazonaws.com/products-service:latest
          name: products-service
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: HTTP_PORT
              value: '3001'
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmquri
                  key: connectionLink
          ports:
            - containerPort: 3001