apiVersion: v1
kind: Service
metadata:
  labels:
    app: products-service
  name: products-service
spec:
  ports:
    - name: 'http'
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: products-service
  type: NodePort