service: supplier-service

useDotenv: true

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
    serverless-offline:
        httpPort: 3000
        lambdaPort: 3009
    customDomain:
      domainName: 'christmas-tree-api.store'
      stage: prod
      createRoute53Record: true
        
provider:
  name: aws
  region: eu-north-1
  runtime: nodejs18.x
  memorySize: 512
  timeout: 30
  endpointType: REGIONAL
  environment:
    RABBITMQ_URI: ${env:RABBITMQ_URI}



package:
  excludeDevDependencies: true
  exclude:
    - ../../node_modules/**
    - ./src/**
    - ./test/**

functions:
  main:
    handler: dist/apps/supplier-service/src/serverless.handler
    events:
      - http:
          method: ANY
          path: /
          cors:
            origins:
              - '*'
      - http:
          method: ANY
          cors:
            origins:
              - '*'
          path: "{proxy+}"