apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: 048443535585.dkr.ecr.eu-north-1.amazonaws.com/auth:latest
          name: auth
          env:
            - name: PORT
              value: '3004'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwtSecret
            - name: JWT_EXPIRATION
              value: '3600'
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmqURI
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
          ports:
            - containerPort: 3004