apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  ports:
    - name: 'http'
      port: 3004
      protocol: TCP
      targetPort: 3004
  selector:
    app: auth
  type: NodePort