apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  ports:
    - name: 'http'
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: order-service
  type: NodePort