apiVersion: v1
kind: Service
metadata:
  labels:
    app: supplier-service
  name: supplier-service
spec:
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: supplier-service
  type: NodePort